# Generated by Django 6.1.1 on 2026-09-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, default='accounts/default.png', null=True, upload_to=''),
        ),
    ]
