# Generated by Django 6.1.1 on 2026-09-14 00:07

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('expired', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=accounts.models.get_expiration_time)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
