# Generated by Django 6.1.1 on 2026-09-22 00:47

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_cpf_account_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAccountRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.get_pending_registration_expiration)),
            ],
        ),
        migrations.CreateModel(
            name='PengingRegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.get_expiration_time)),
                ('expired', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('pending_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='accounts.pendingaccountregistration')),
            ],
        ),
    ]
