# Generated by Django 6.1.1 on 2026-09-21 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_cpf_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF must contain exactly 11 digits.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 or 11 digits.', regex='^\\d{10,11}$')]),
        ),
    ]
