# Generated by Django 6.1.1 on 2026-09-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_pendingaccountregistration_pengingregistrationtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PengingRegistrationToken',
            new_name='PendingRegistrationToken',
        ),
    ]
