# Generated by Django 6.1.1 on 2026-09-28 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_smscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='The SMS code must contain exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
