# Generated by Django 6.1.1 on 2026-09-28 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_smscode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 or 11 digits.', regex='^\\d{10,11}$')]),
        ),
    ]
